#!/bin/bash

# This will allow you to rapidly create a vhost configuration for your project.
# IT adds a vhost to your vhost file (apache) and adds an entyr in the hosts
# file.
#
# Note: this is created for Mac OS X.
configure-vhost()
{
    projectName=$1
    projectPath=$2

    if [[ "$projectName" == "" ]]; then
        tput setaf 1
        read -p "Please, specify a project name (${PWD##*/}): "
        tput sgr0
        projectName=$REPLY
        if [[ "$REPLY" == "" ]]; then
            projectName=${PWD##*/}
        fi
    fi

    if [[ "$projectPath" == "" ]]; then
        tput setaf 3
        read -p "Please, specify a project path ($PWD): "
        tput sgr0

        projectPath=$REPLY
        if [[ "$REPLY" == "" ]]; then
            projectPath=$PWD
        fi
    fi

    # Create our vhost.
    echo -e "127.0.0.1\t\t\t$projectName.dev" | sudo tee -a /etc/hosts > /dev/null;
    echo -e "\n# $projectName.dev" | sudo tee -a /etc/apache2/extra/httpd-vhosts.conf > /dev/null;
    echo -e "<VirtualHost *:80>" | sudo tee -a /etc/apache2/extra/httpd-vhosts.conf > /dev/null;
    echo -e "\tServerAdmin jelmer.snoeck@siphoc.com" | sudo tee -a /etc/apache2/extra/httpd-vhosts.conf > /dev/null;
    echo -e "\tDocumentRoot \"$projectPath\"" | sudo tee -a /etc/apache2/extra/httpd-vhosts.conf > /dev/null;
    echo -e "\tServerName $projectName.dev" | sudo tee -a /etc/apache2/extra/httpd-vhosts.conf > /dev/null;
    echo -e "\tServerAlias $projectName.*.xip.io" | sudo tee -a /etc/apache2/extra/httpd-vhosts.conf > /dev/null;
    echo -e "\tErrorLog \"/private/var/log/apache2/$projectName-error_log\"" | sudo tee -a /etc/apache2/extra/httpd-vhosts.conf > /dev/null;
    echo -e "\tCustomLog \"/private/var/log/apache2/$projectName-access_log\" common" | sudo tee -a /etc/apache2/extra/httpd-vhosts.conf > /dev/null;
    echo -e "</virtualHost>" | sudo tee -a /etc/apache2/extra/httpd-vhosts.conf > /dev/null;
    echo "VirtualHost $projectName.dev created.";

    # Restart apache to enable our newly created vhost.
    sudo apachectl graceful;
    echo "Apache server restarted.";
}
