#!/usr/bin/env bash

# Set OS type
export OS=`uname -s`

# Path
export PATH="$HOME/.bin:$PATH"
export PATH=$PATH:/usr/local/sbin
export PATH=/usr/local/share/npm/bin:$PATH
export PATH="./.bundle/bin:$PATH"

# Disable Homebrew analytics gathering
export HOMEBREW_NO_ANALYTICS=1

# Set up editor to Vim
export EDITOR='vim';

# Golang exports
export GOPATH="/Users/jelmersnoeck/go"
export PATH=$PATH:$GOPATH/bin

# CDPATH allows you to easily cd into paths without having to type the full path
export CDPATH=.:$HOME:$GOPATH/src:$GOPATH/src/golang.org:$GOPATH/src/github.com:

# grep
export GREP_OPTIONS='--color=auto'

export PATH=$PATH:$HOME/.linkerd2/bin
